project_id = "kbghvclwhxnjeskdodeh"

[functions.get-weather]
verify_jwt = false

[functions.seed-promo-banner]
verify_jwt = true


[functions.reset-season]
verify_jwt = false

[functions.terra-webhook]
verify_jwt = false
