project_id = "kbghvclwhxnjeskdodeh"

[functions.get-weather]
verify_jwt = false

[functions.seed-promo-banner]
verify_jwt = true


[functions.reset-season]
verify_jwt = false

[functions.terra-webhook]
verify_jwt = false

[functions.terra-webhook-test]
verify_jwt = false

[functions.weekly-plan-review]
verify_jwt = false

[functions.generate-share-poster]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.analyze-posture]
verify_jwt = false

[functions.analyze-activity]
verify_jwt = false
