import { useState, useEffect } from "react";
import { Globe, Smartphone, ChevronRight, CheckCircle2, Check, X, Crown, Sparkles, Target, KeyRound } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { motion } from "framer-motion";
import appStoreBadge from "@/assets/app-store-badge.png";
import appIcon from "@/assets/app-icon.png";
import poweredByStrava from "@/assets/powered-by-strava.png";
import IPhoneFrame from "@/components/landing/IPhoneFrame";
import heroEn from "@/assets/appstore/hero-en.png.asset.json";
import heroZh from "@/assets/appstore/hero-zh.png.asset.json";
import FeatureShowcase from "@/components/landing/FeatureShowcase";
import AppStoreScreenshots from "@/components/landing/AppStoreScreenshots";
import DashboardPreview from "@/components/landing/DashboardPreview";
import HeroPhoneStack from "@/components/landing/HeroPhoneStack";
import HeroStats from "@/components/landing/HeroStats";

import rewardsScreenshot from "@/assets/screenshots/rewards.png";
import trainingScreenshot from "@/assets/screenshots/training.png";
import racesScreenshot from "@/assets/screenshots/races.png";
import postureScreenshot from "@/assets/screenshots/posture.png";
import calculatorScreenshot from "@/assets/screenshots/calculator.png";

import rewardsScreenshotZh from "@/assets/screenshots/rewards-zh.png";
import trainingScreenshotZh from "@/assets/screenshots/training-zh.png";
import racesScreenshotZh from "@/assets/screenshots/races-zh.png";
import postureScreenshotZh from "@/assets/screenshots/posture-zh.png";
import calculatorScreenshotZh from "@/assets/screenshots/calculator-zh.png";

const APP_STORE_URL = "https://apps.apple.com/us/app/runward/id6761060757";

type Lang = "en" | "zh";

const Landing = () => {
  const location = useLocation();
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("app_lang") as Lang) || "en");
  const currentRoute = `${location.pathname}${location.search}`;
  const toggleLang = () => {
    const next = lang === "en" ? "zh" : "en";
    localStorage.setItem("app_lang", next);
    setLang(next);
  };

  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setVisible(true), 100);
    return () => clearTimeout(t);
  }, []);

  const zh = lang === "zh";

  const features = [
    {
      badge: zh ? "排名系統" : "RANKED SEASONS",
      title: zh ? "攀升排名，贏取獎勵" : "Climb Ranks. Win Rewards.",
      desc: zh
        ? "每日簽到賺取 XP，攀升 Bronze 至 Diamond 的排名階梯。登上排行榜，頂尖跑者可贏取 App Store 兌換碼。"
        : "Earn XP from daily check-ins and activity syncs. Climb from Bronze to Diamond, compete on leaderboards, and win App Store redeem codes.",
      screenshot: zh ? rewardsScreenshotZh : rewardsScreenshot,
      alt: "Rewards & Ranked Seasons",
    },
    {
      badge: zh ? "AI 訓練" : "AI TRAINING",
      title: zh ? "AI 量身定制訓練計劃" : "AI-Personalized Training Plans",
      desc: zh
        ? "根據你的體能水平，AI 為你生成馬拉松及半馬訓練計劃，每週配速、距離一目了然。"
        : "Get marathon & half-marathon plans generated by AI, tailored to your fitness level with precise paces and weekly mileage.",
      screenshot: zh ? trainingScreenshotZh : trainingScreenshot,
      alt: "AI Training Plans",
    },
    {
      badge: zh ? "比賽搜尋" : "RACE FINDER",
      title: zh ? "探索全球比賽" : "Discover Races Worldwide",
      desc: zh
        ? "搜尋即將舉行的比賽，按距離篩選，提交及分享你所在地區的賽事。"
        : "Find upcoming races near you. Filter by distance, browse by country, and share events with the running community.",
      screenshot: zh ? racesScreenshotZh : racesScreenshot,
      alt: "Race Calendar",
    },
    {
      badge: zh ? "跑姿分析" : "POSTURE ANALYSIS",
      title: zh ? "用相機分析跑步姿勢" : "Analyze Your Running Form",
      desc: zh
        ? "使用相機分析跑步姿勢，獲取頭部、肩膀、軀幹及四肢的評分反饋與雷達圖。"
        : "Use your camera to analyze running form. Get scored feedback on head, shoulder, torso, and limb alignment with a radar chart.",
      screenshot: zh ? postureScreenshotZh : postureScreenshot,
      alt: "Posture Analysis",
    },
    {
      badge: zh ? "訓練配速" : "PACE CALCULATOR",
      title: zh ? "計算跑步分數與配速" : "Your Score. Your Paces.",
      desc: zh
        ? "計算你的跑步分數、訓練配速、等效比賽時間，涵蓋所有距離。"
        : "Calculate your Running Score, training paces for every zone, and equivalent race times across all distances.",
      screenshot: zh ? calculatorScreenshotZh : calculatorScreenshot,
      alt: "Pace Calculator",
    },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground font-body overflow-x-hidden">
      {/* ─── Nav ─── */}
      <nav className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border/50">
        <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-3">
          <div className="flex items-center gap-2.5">
            <img src={appIcon} alt="Runward" className="h-8 w-8 rounded-lg" />
            <span className="font-display font-bold text-lg">{zh ? "向前跑" : "Runward"}</span>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="#pricing"
              className="hidden sm:inline-block text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              {zh ? "價格" : "Pricing"}
            </a>
            <button
              onClick={toggleLang}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-card border border-border text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              <Globe size={14} />
              {lang === "en" ? "中文" : "EN"}
            </button>
            <Link
              to="/dashboard?auth=1"
              className="hidden sm:inline-flex items-center gap-2 px-4 py-2 rounded-full bg-card border border-border text-sm font-semibold text-foreground hover:bg-muted transition-colors"
            >
              <KeyRound size={14} />
              {zh ? "登入 / 註冊" : "Sign In"}
            </Link>
            <Link
              to="/dashboard"
              className="hidden sm:inline-flex items-center gap-2 px-4 py-2 rounded-full bg-card border border-border text-sm font-semibold text-foreground hover:bg-muted transition-colors"
            >
              <Target size={14} />
              {zh ? "儀表板" : "Dashboard"}
            </Link>
            <a
              href={APP_STORE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="hidden sm:inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 transition-colors"
            >
              <Smartphone size={14} />
              {zh ? "下載" : "Download"}
            </a>
          </div>
        </div>
      </nav>

      {/* ─── Hero (dark, dappr-style) ─── */}
      <section className="relative bg-[#1a1a1a] text-white overflow-hidden">
        {/* Warm highlight top-right */}
        <div className="pointer-events-none absolute top-[-200px] right-[-150px] w-[700px] h-[700px] rounded-full blur-3xl"
          style={{ background: "radial-gradient(circle, rgba(255,200,140,0.18), transparent 60%)" }} />
        {/* Mint glow center-right */}
        <div className="pointer-events-none absolute top-1/3 right-[10%] w-[500px] h-[500px] rounded-full blur-3xl"
          style={{ background: "radial-gradient(circle, hsl(var(--primary) / 0.15), transparent 65%)" }} />

        <div className="relative z-10 max-w-6xl mx-auto px-6 pt-16 md:pt-24 pb-10 md:pb-16 grid md:grid-cols-[1.05fr_1fr] gap-12 md:gap-10 items-center">
          {/* Left — copy */}
          <div className={`transition-all duration-700 ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-6"}`}>
            <h1 className="font-display text-[2.75rem] sm:text-5xl md:text-6xl lg:text-[4.5rem] font-bold tracking-tight leading-[1.02] text-white">
              {zh
                ? "你需要的一切，讓訓練更有方向。"
                : "Everything you need to train, race, and improve."}
            </h1>

            <p className="text-base md:text-lg text-white/70 leading-relaxed max-w-xl mt-6 md:mt-8">
              {zh
                ? "成為首批使用 AI 跑步教練的跑者 — Strava、Garmin、Apple Health 一鍵同步，訓練、比賽、分析全部整合。"
                : "Be among the first runners to experience the easiest way to train smarter — wearables, AI plans, races and analytics in one app."}
            </p>

            <div className="mt-8 md:mt-10 flex items-center gap-6 flex-wrap">
              <a
                href={APP_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-7 py-3.5 rounded-full bg-primary text-primary-foreground text-base font-bold hover:bg-primary/90 transition-colors shadow-[0_0_40px_hsl(var(--primary)/0.45)]"
              >
                {zh ? "免費下載" : "Get the app"}
              </a>
              <a
                href="#features"
                className="inline-flex items-center text-base font-semibold text-white border-b-2 border-white/40 hover:border-white pb-0.5 transition-colors"
              >
                {zh ? "查看功能" : "View features"}
              </a>
            </div>

            <p className="text-xs text-white/50 mt-5">
              {zh ? "iPhone · 免費下載 · 7 天 Premium 試用" : "iPhone · Free to download · 7-day Premium trial"}
            </p>
          </div>

          {/* Right — phone stack with glowing widgets */}
          <div className={`relative transition-all duration-700 delay-200 ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
            <HeroPhoneStack lang={lang} />
          </div>
        </div>

        {/* Product stats strip */}
        <div className="relative z-10 max-w-6xl mx-auto px-6 pb-14 md:pb-20">
          <HeroStats lang={lang} />
        </div>
      </section>


      {/* ─── Feature Showcases ─── */}
      <section className="px-6 py-20 md:py-28">
        <div className="max-w-5xl mx-auto space-y-24 md:space-y-32">
          {features.map((f, i) => (
            <FeatureShowcase
              key={i}
              badge={f.badge}
              title={f.title}
              description={f.desc}
              screenshot={f.screenshot}
              screenshotAlt={f.alt}
              reverse={i % 2 === 1}
            />
          ))}
        </div>
      </section>

      {/* ─── App Store Screenshots ─── */}
      <AppStoreScreenshots lang={lang} />

      {/* ─── Web Dashboard Preview ─── */}
      <DashboardPreview lang={lang} />



      {/* ─── Pricing ─── */}
      <section id="pricing" className="px-6 py-20 md:py-28 bg-card/30 border-y border-border">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <span className="inline-block px-3 py-1 rounded-full bg-primary/15 text-primary text-xs font-semibold tracking-wide uppercase mb-4">
              {zh ? "訂閱方案" : "Pricing"}
            </span>
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
              {zh ? "簡單透明的訂閱方案" : "Simple, Transparent Pricing"}
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              {zh ? "免費開始,隨時升級為 Premium。" : "Start for free. Upgrade to Premium when you're ready."}
            </p>
          </div>





          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {/* Free */}
            <div className="rounded-2xl border border-border bg-background p-6 flex flex-col">
              <div className="mb-4">
                <h3 className="font-display text-xl font-bold mb-1">{zh ? "免費版" : "Free"}</h3>
                <p className="text-sm text-muted-foreground">{zh ? "開始你的跑步旅程" : "Start your running journey"}</p>
              </div>
              <div className="mb-6">
                <span className="font-display text-4xl font-bold">{zh ? "免費" : "Free"}</span>
              </div>
              <ul className="space-y-2.5 text-sm mb-6 flex-1">
                {[
                  zh ? "活動追蹤與同步" : "Activity tracking & sync",
                  zh ? "社群與排行榜" : "Community & leaderboards",
                  zh ? "HRV 洞察" : "HRV insights",
                  zh ? "訓練負荷圖表" : "Training load charts",
                  zh ? "基本訓練計劃" : "Basic training plans",
                  zh ? "每日 1 次跑姿分析" : "1 posture analysis / day",
                ].map((f, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <Check size={16} className="text-success shrink-0 mt-0.5" />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <a
                href={APP_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-full border border-border text-sm font-semibold hover:bg-muted transition-colors"
              >
                {zh ? "免費下載" : "Download Free"}
              </a>
            </div>

            {/* Monthly */}
            <div className="rounded-2xl border border-border bg-background p-6 flex flex-col">
              <div className="mb-4">
                <h3 className="font-display text-xl font-bold mb-1 flex items-center gap-2">
                  Premium <span className="text-xs font-normal text-muted-foreground">{zh ? "月費" : "Monthly"}</span>
                </h3>
                <p className="text-sm text-muted-foreground">{zh ? "彈性月度訂閱" : "Flexible monthly billing"}</p>
              </div>
              <div className="mb-6">
                <span className="font-display text-4xl font-bold">HK$48</span>
                <span className="text-muted-foreground">/{zh ? "月" : "mo"}</span>
                <div className="text-sm text-muted-foreground mt-1">TWD 190/{zh ? "月" : "mo"}</div>
              </div>

              <ul className="space-y-2.5 text-sm mb-6 flex-1">
                {[
                  zh ? "包含所有免費功能" : "Everything in Free",
                  zh ? "AI 跑步教練（24/7）" : "AI Running Coach (24/7)",
                  zh ? "AI 活動分析報告" : "AI activity analysis",
                  zh ? "AI 個人化訓練計劃" : "AI-personalized training plans",
                  zh ? "無限跑姿分析" : "Unlimited posture analysis",
                  zh ? "全距離比賽預測" : "Race predictor (all distances)",
                ].map((f, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <Check size={16} className="text-primary shrink-0 mt-0.5" />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <a
                href={APP_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-full bg-foreground text-background text-sm font-semibold hover:bg-foreground/90 transition-colors"
              >
                {zh ? "立即訂閱" : "Subscribe"}
              </a>
            </div>

            {/* Yearly */}
            <div className="relative rounded-2xl border-2 border-primary bg-gradient-to-br from-primary/10 via-primary/5 to-background p-6 flex flex-col shadow-lg">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-primary text-primary-foreground text-[11px] font-bold tracking-wide uppercase">
                {zh ? "最划算" : "Best Value"}
              </div>
              <div className="mb-4">
                <h3 className="font-display text-xl font-bold mb-1 flex items-center gap-2">
                  Premium <span className="text-xs font-normal text-muted-foreground">{zh ? "年費" : "Yearly"}</span>
                </h3>
                <p className="text-sm text-muted-foreground">{zh ? "節省更多，承諾全年" : "Save more, commit to the year"}</p>
              </div>
              <div className="mb-6">
                <span className="font-display text-4xl font-bold">HK$488</span>
                <span className="text-muted-foreground">/{zh ? "年" : "yr"}</span>
                <div className="text-sm text-muted-foreground mt-1">TWD 1990/{zh ? "年" : "yr"}</div>
              </div>
              <ul className="space-y-2.5 text-sm mb-6 flex-1">
                {[
                  zh ? "包含所有月費功能" : "Everything in Monthly",
                  zh ? "相當於每月約 HK$41" : "About HK$41 / month",
                  zh ? "年費省更多" : "Save more annually",
                  zh ? "AI 活動分享海報" : "AI activity share posters",
                  zh ? "每週計劃回顧（即將推出）" : "Weekly plan reviews (soon)",
                  zh ? "優先獲取新功能" : "Priority access to new features",
                ].map((f, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <Sparkles size={16} className="text-warning shrink-0 mt-0.5" />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <a
                href={APP_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-full bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 transition-colors"
              >
                <Crown size={14} />
                {zh ? "立即訂閱" : "Subscribe Yearly"}
              </a>
            </div>
          </div>



          {/* Comparison table */}
          <div className="mt-16 max-w-3xl mx-auto">
            <h3 className="font-display text-2xl md:text-3xl font-bold text-center mb-2">
              {zh ? "免費版 vs Premium" : "Free vs Premium"}
            </h3>
            <p className="text-center text-muted-foreground mb-8 text-sm">
              {zh ? "完整功能對照" : "Full feature comparison"}
            </p>
            <div className="bg-background border border-border rounded-2xl overflow-hidden">
              <div className="grid grid-cols-[1fr_100px_100px] md:grid-cols-[1fr_140px_140px] bg-accent/50 px-4 py-3 text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                <span>{zh ? "功能" : "Feature"}</span>
                <span className="text-center">{zh ? "免費" : "Free"}</span>
                <span className="text-center flex items-center justify-center gap-1">
                  <Sparkles size={12} className="text-warning" />
                  Premium
                </span>
              </div>
              {[
                { label: zh ? "活動追蹤與同步" : "Activity tracking & sync", free: true, premium: true },
                { label: zh ? "社群與排行榜" : "Community & leaderboards", free: true, premium: true },
                { label: zh ? "HRV 洞察" : "HRV insights", free: true, premium: true },
                { label: zh ? "訓練負荷圖表" : "Training load charts", free: true, premium: true },
                { label: zh ? "AI 跑步教練（全天候）" : "AI Running Coach (24/7 chat)", free: false, premium: true },
                { label: zh ? "AI 活動分析" : "AI activity analysis", free: false, premium: true },
                { label: zh ? "活動分享" : "Activity sharing", free: zh ? "基本" : "Basic", premium: zh ? "全部功能" : "All functions" },
                { label: zh ? "AI 活動分享海報" : "AI activity share posters", free: false, premium: true },
                { label: zh ? "每週計劃回顧" : "Weekly plan reviews", free: false, premium: zh ? "即將推出" : "Coming soon" },
                { label: zh ? "訓練計劃" : "Training plans", free: zh ? "基本" : "Basic", premium: zh ? "AI 個人化" : "Personalized AI" },
                { label: zh ? "比賽預測" : "Race predictor", free: zh ? "僅 5K" : "5K only", premium: zh ? "全距離" : "All distances" },
                { label: zh ? "跑姿分析" : "Posture analysis", free: zh ? "每日 1 次" : "1 / day", premium: zh ? "無限" : "Unlimited" },
              ].map((f, i) => (
                <div
                  key={i}
                  className={`grid grid-cols-[1fr_100px_100px] md:grid-cols-[1fr_140px_140px] items-center px-4 py-3 text-sm ${
                    i % 2 === 0 ? "bg-background" : "bg-accent/20"
                  }`}
                >
                  <span className="text-foreground pr-2">{f.label}</span>
                  <div className="text-center">
                    {f.free === true ? (
                      <Check size={16} className="text-success mx-auto" />
                    ) : f.free === false ? (
                      <X size={16} className="text-muted-foreground/50 mx-auto" />
                    ) : (
                      <span className="text-xs text-foreground">{f.free}</span>
                    )}
                  </div>
                  <div className="text-center">
                    {f.premium === true ? (
                      <Check size={16} className="text-success mx-auto" />
                    ) : f.premium === false ? (
                      <X size={16} className="text-muted-foreground/50 mx-auto" />
                    ) : (
                      <span className="text-xs text-foreground">{f.premium}</span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ─── Premium CTA ─── */}
      <section className="px-6 py-20 md:py-28">
        <div className="max-w-4xl mx-auto">
          <motion.div
            className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary/10 via-primary/5 to-background border border-primary/20 p-8 md:p-12"
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl pointer-events-none" />
            <div className="relative z-10 grid md:grid-cols-2 gap-8 items-center">
              <div>
                <span className="inline-block px-3 py-1 rounded-full bg-primary/15 text-primary text-xs font-semibold mb-4">
                  {zh ? "進階版" : "PREMIUM"}
                </span>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  {zh ? "解鎖完整體驗" : "Unlock the Full Experience"}
                </h2>
                <p className="text-muted-foreground mb-6">
                  {zh
                    ? "升級進階版，獲取 AI 訓練計劃、跑姿分析及更多專屬功能。"
                    : "Upgrade to Premium for AI training plans, posture analysis, and exclusive features."}
                </p>
                <a
                  href={APP_STORE_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-colors"
                >
                  {zh ? "下載應用，立即體驗" : "Get the App & Try Premium"}
                  <ChevronRight size={16} />
                </a>
              </div>
              <div className="space-y-3">
                {[
                  zh ? "AI 個人化訓練計劃" : "AI-Personalized Training Plans",
                  zh ? "即時跑姿分析" : "Real-time Posture Analysis",
                  zh ? "AI 活動分析報告" : "AI Activity Analysis Reports",
                  zh ? "無限制訓練計劃生成" : "Unlimited Plan Generation",
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <CheckCircle2 size={18} className="text-primary shrink-0" />
                    <span className="text-sm font-medium">{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── Final CTA ─── */}
      <section className="px-6 py-20 md:py-28 bg-card/50">
        <motion.div
          className="max-w-lg mx-auto text-center space-y-6"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <img src={appIcon} alt="Runward" className="h-20 w-20 rounded-2xl shadow-lg mx-auto" />
          <h2 className="font-display text-2xl md:text-3xl font-bold">
            {zh ? "準備好跑得更聰明了嗎？" : "Ready to Run Smarter?"}
          </h2>
          <p className="text-muted-foreground">
            {zh
              ? "加入 Runward，讓 AI 幫助你達成跑步目標。"
              : "Join Runward and let AI help you reach your running goals."}
          </p>
          <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" className="inline-block">
            <img src={appStoreBadge} alt="Download on the App Store" className="h-14 mx-auto" />
          </a>
        </motion.div>
      </section>

      {/* ─── Footer ─── */}
      <footer className="px-6 py-8 border-t border-border">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-muted-foreground">
          <div className="flex items-center gap-3">
            <img src={appIcon} alt="" className="h-5 w-5 rounded" />
            <span>© {new Date().getFullYear()} {zh ? "向前跑" : "Runward"}. {zh ? "保留所有權利。" : "All rights reserved."}</span>
            <span className="text-border">|</span>
            <img src={poweredByStrava} alt="Powered by Strava" className="h-5 rounded-sm px-1" style={{ backgroundColor: "#F7F7F7" }} />
          </div>
          <div className="flex gap-6">
            <Link to="/privacy" state={{ from: currentRoute }} className="hover:text-foreground transition-colors">
              {zh ? "隱私政策" : "Privacy Policy"}
            </Link>
            <Link to="/support" state={{ from: currentRoute }} className="hover:text-foreground transition-colors">
              {zh ? "支援" : "Support"}
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
