import { useState, useEffect } from "react";
import { Globe, Smartphone, ChevronRight, CheckCircle2, Check, X, Crown, Sparkles } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { motion } from "framer-motion";
import appStoreBadge from "@/assets/app-store-badge.png";
import appIcon from "@/assets/app-icon.png";
import poweredByStrava from "@/assets/powered-by-strava.png";
import IPhoneFrame from "@/components/landing/IPhoneFrame";
import FeatureShowcase from "@/components/landing/FeatureShowcase";

import rewardsScreenshot from "@/assets/screenshots/rewards.png";
import trainingScreenshot from "@/assets/screenshots/training.png";
import racesScreenshot from "@/assets/screenshots/races.png";
import postureScreenshot from "@/assets/screenshots/posture.png";
import calculatorScreenshot from "@/assets/screenshots/calculator.png";

import rewardsScreenshotZh from "@/assets/screenshots/rewards-zh.png";
import trainingScreenshotZh from "@/assets/screenshots/training-zh.png";
import racesScreenshotZh from "@/assets/screenshots/races-zh.png";
import postureScreenshotZh from "@/assets/screenshots/posture-zh.png";
import calculatorScreenshotZh from "@/assets/screenshots/calculator-zh.png";

const APP_STORE_URL = "https://apps.apple.com/us/app/runward/id6761060757";

type Lang = "en" | "zh";

const Landing = () => {
  const location = useLocation();
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("app_lang") as Lang) || "en");
  const currentRoute = `${location.pathname}${location.search}`;
  const toggleLang = () => {
    const next = lang === "en" ? "zh" : "en";
    localStorage.setItem("app_lang", next);
    setLang(next);
  };

  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setVisible(true), 100);
    return () => clearTimeout(t);
  }, []);

  const zh = lang === "zh";

  const features = [
    {
      badge: zh ? "排名系統" : "RANKED SEASONS",
      title: zh ? "攀升排名，贏取獎勵" : "Climb Ranks. Win Rewards.",
      desc: zh
        ? "每日簽到賺取 XP，攀升 Bronze 至 Diamond 的排名階梯。登上排行榜，頂尖跑者可贏取 App Store 兌換碼。"
        : "Earn XP from daily check-ins and activity syncs. Climb from Bronze to Diamond, compete on leaderboards, and win App Store redeem codes.",
      screenshot: zh ? rewardsScreenshotZh : rewardsScreenshot,
      alt: "Rewards & Ranked Seasons",
    },
    {
      badge: zh ? "AI 訓練" : "AI TRAINING",
      title: zh ? "AI 量身定制訓練計劃" : "AI-Personalized Training Plans",
      desc: zh
        ? "根據你的體能水平，AI 為你生成馬拉松及半馬訓練計劃，每週配速、距離一目了然。"
        : "Get marathon & half-marathon plans generated by AI, tailored to your fitness level with precise paces and weekly mileage.",
      screenshot: zh ? trainingScreenshotZh : trainingScreenshot,
      alt: "AI Training Plans",
    },
    {
      badge: zh ? "比賽搜尋" : "RACE FINDER",
      title: zh ? "探索全球比賽" : "Discover Races Worldwide",
      desc: zh
        ? "搜尋即將舉行的比賽，按距離篩選，提交及分享你所在地區的賽事。"
        : "Find upcoming races near you. Filter by distance, browse by country, and share events with the running community.",
      screenshot: zh ? racesScreenshotZh : racesScreenshot,
      alt: "Race Calendar",
    },
    {
      badge: zh ? "跑姿分析" : "POSTURE ANALYSIS",
      title: zh ? "用相機分析跑步姿勢" : "Analyze Your Running Form",
      desc: zh
        ? "使用相機分析跑步姿勢，獲取頭部、肩膀、軀幹及四肢的評分反饋與雷達圖。"
        : "Use your camera to analyze running form. Get scored feedback on head, shoulder, torso, and limb alignment with a radar chart.",
      screenshot: zh ? postureScreenshotZh : postureScreenshot,
      alt: "Posture Analysis",
    },
    {
      badge: zh ? "訓練配速" : "PACE CALCULATOR",
      title: zh ? "計算跑步分數與配速" : "Your Score. Your Paces.",
      desc: zh
        ? "計算你的跑步分數、訓練配速、等效比賽時間，涵蓋所有距離。"
        : "Calculate your Running Score, training paces for every zone, and equivalent race times across all distances.",
      screenshot: zh ? calculatorScreenshotZh : calculatorScreenshot,
      alt: "Pace Calculator",
    },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground font-body overflow-x-hidden">
      {/* ─── Nav ─── */}
      <nav className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border/50">
        <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-3">
          <div className="flex items-center gap-2.5">
            <img src={appIcon} alt="Runward" className="h-8 w-8 rounded-lg" />
            <span className="font-display font-bold text-lg">{zh ? "向前跑" : "Runward"}</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={toggleLang}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-card border border-border text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              <Globe size={14} />
              {lang === "en" ? "中文" : "EN"}
            </button>
            <a
              href={APP_STORE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="hidden sm:inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 transition-colors"
            >
              <Smartphone size={14} />
              {zh ? "下載" : "Download"}
            </a>
          </div>
        </div>
      </nav>

      {/* ─── Hero ─── */}
      <section className="relative px-6 pt-20 pb-28 md:pt-28 md:pb-36 overflow-hidden">
        {/* BG blurs */}
        <div className="absolute top-[-200px] left-1/2 -translate-x-1/2 w-[900px] h-[900px] rounded-full bg-primary/6 blur-3xl pointer-events-none" />
        <div className="absolute top-20 -right-32 w-80 h-80 rounded-full bg-primary/8 blur-3xl pointer-events-none" />

        <div className="relative z-10 max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">
          {/* Left — copy */}
          <div className={`transition-all duration-700 ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-6"}`}>
            <div className="flex items-center gap-3 mb-6">
              <img src={appIcon} alt="" className="h-14 w-14 rounded-2xl shadow-lg ring-1 ring-border" />
              <div>
                <h1 className="font-display text-4xl sm:text-5xl md:text-[3.25rem] font-bold tracking-tight leading-[1.1]">
                  {zh ? "你的 AI 跑步教練" : "Run Smarter."}
                </h1>
              </div>
            </div>
            {!zh && (
              <h1 className="font-display text-4xl sm:text-5xl md:text-[3.25rem] font-bold tracking-tight leading-[1.1] -mt-2 mb-6">
                <span className="text-primary">Train Better.</span>
              </h1>
            )}
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed max-w-lg mb-8">
              {zh
                ? "AI 訓練計劃、跑姿分析、排名賽季獎勵 — 跑得更聰明，盡在一個應用。"
                : "AI training plans, posture analysis, ranked seasons & rewards — everything a runner needs in one beautifully crafted app."}
            </p>
            <div className="flex flex-col sm:flex-row items-start gap-4">
              <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer">
                <img src={appStoreBadge} alt="Download on the App Store" className="h-14" />
              </a>
              <span className="text-sm text-muted-foreground mt-2 sm:mt-4">
                {zh ? "免費下載 · 支援 iPhone" : "Free · iPhone"}
              </span>
            </div>
          </div>

          {/* Right — hero phones */}
          <div className={`relative flex justify-center items-end gap-4 transition-all duration-700 delay-200 ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
            <div className="relative -rotate-6 translate-y-4">
              <IPhoneFrame src={zh ? trainingScreenshotZh : trainingScreenshot} alt="Training" className="w-[180px] md:w-[210px]" />
            </div>
            <div className="relative z-10">
              <IPhoneFrame src={zh ? rewardsScreenshotZh : rewardsScreenshot} alt="Rewards" className="w-[200px] md:w-[240px]" />
            </div>
            <div className="relative rotate-6 translate-y-4">
              <IPhoneFrame src={zh ? racesScreenshotZh : racesScreenshot} alt="Races" className="w-[180px] md:w-[210px]" />
            </div>
          </div>
        </div>
      </section>

      {/* ─── Social proof strip ─── */}
      <section className="border-y border-border bg-card/50">
        <div className="max-w-5xl mx-auto grid grid-cols-3 divide-x divide-border">
          {[
            { value: zh ? "AI 教練" : "AI Coach", label: zh ? "個人化訓練" : "Personalized Plans" },
            { value: zh ? "跑者排名" : "Ranked", label: zh ? "賽季制度" : "Seasonal Leagues" },
            { value: zh ? "免費" : "Free", label: zh ? "核心功能" : "Core Features" },
          ].map((stat, i) => (
            <div key={i} className="flex flex-col items-center py-5 px-4 text-center">
              <span className="font-display font-bold text-foreground text-lg">{stat.value}</span>
              <span className="text-xs text-muted-foreground mt-0.5">{stat.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Feature Showcases ─── */}
      <section className="px-6 py-20 md:py-28">
        <div className="max-w-5xl mx-auto space-y-24 md:space-y-32">
          {features.map((f, i) => (
            <FeatureShowcase
              key={i}
              badge={f.badge}
              title={f.title}
              description={f.desc}
              screenshot={f.screenshot}
              screenshotAlt={f.alt}
              reverse={i % 2 === 1}
            />
          ))}
        </div>
      </section>

      {/* ─── Premium CTA ─── */}
      <section className="px-6 py-20 md:py-28">
        <div className="max-w-4xl mx-auto">
          <motion.div
            className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary/10 via-primary/5 to-background border border-primary/20 p-8 md:p-12"
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl pointer-events-none" />
            <div className="relative z-10 grid md:grid-cols-2 gap-8 items-center">
              <div>
                <span className="inline-block px-3 py-1 rounded-full bg-primary/15 text-primary text-xs font-semibold mb-4">
                  {zh ? "進階版" : "PREMIUM"}
                </span>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  {zh ? "解鎖完整體驗" : "Unlock the Full Experience"}
                </h2>
                <p className="text-muted-foreground mb-6">
                  {zh
                    ? "升級進階版，獲取 AI 訓練計劃、跑姿分析及更多專屬功能。"
                    : "Upgrade to Premium for AI training plans, posture analysis, and exclusive features."}
                </p>
                <a
                  href={APP_STORE_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-colors"
                >
                  {zh ? "下載應用，立即體驗" : "Get the App & Try Premium"}
                  <ChevronRight size={16} />
                </a>
              </div>
              <div className="space-y-3">
                {[
                  zh ? "AI 個人化訓練計劃" : "AI-Personalized Training Plans",
                  zh ? "即時跑姿分析" : "Real-time Posture Analysis",
                  zh ? "AI 活動分析報告" : "AI Activity Analysis Reports",
                  zh ? "無限制訓練計劃生成" : "Unlimited Plan Generation",
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <CheckCircle2 size={18} className="text-primary shrink-0" />
                    <span className="text-sm font-medium">{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── Final CTA ─── */}
      <section className="px-6 py-20 md:py-28 bg-card/50">
        <motion.div
          className="max-w-lg mx-auto text-center space-y-6"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <img src={appIcon} alt="Runward" className="h-20 w-20 rounded-2xl shadow-lg mx-auto" />
          <h2 className="font-display text-2xl md:text-3xl font-bold">
            {zh ? "準備好跑得更聰明了嗎？" : "Ready to Run Smarter?"}
          </h2>
          <p className="text-muted-foreground">
            {zh
              ? "加入 Runward，讓 AI 幫助你達成跑步目標。"
              : "Join Runward and let AI help you reach your running goals."}
          </p>
          <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" className="inline-block">
            <img src={appStoreBadge} alt="Download on the App Store" className="h-14 mx-auto" />
          </a>
        </motion.div>
      </section>

      {/* ─── Footer ─── */}
      <footer className="px-6 py-8 border-t border-border">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-muted-foreground">
          <div className="flex items-center gap-3">
            <img src={appIcon} alt="" className="h-5 w-5 rounded" />
            <span>© {new Date().getFullYear()} {zh ? "向前跑" : "Runward"}. {zh ? "保留所有權利。" : "All rights reserved."}</span>
            <span className="text-border">|</span>
            <img src={poweredByStrava} alt="Powered by Strava" className="h-5 rounded-sm px-1" style={{ backgroundColor: "#F7F7F7" }} />
          </div>
          <div className="flex gap-6">
            <Link to="/privacy" state={{ from: currentRoute }} className="hover:text-foreground transition-colors">
              {zh ? "隱私政策" : "Privacy Policy"}
            </Link>
            <Link to="/support" state={{ from: currentRoute }} className="hover:text-foreground transition-colors">
              {zh ? "支援" : "Support"}
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
